print("Tablero: 8x8 casillas, alternando colores claros y oscuros")
print("Piezas: Cada jugador inicia con 16 (rey, dama, 2 torres, 2 alfiles, 2 caballos, 8 peones).")
print("Objetivo: Dar jaque mate (rey atacado sin escapatoria).")
print("Movimientos: Peón: Avanza recto, captura en diagonal. En salida, puede avanzar 2 casillas.Torre: Horizontal/vertical.Caballo: En ele (2+1 casillas).Alfil: Diagonal.Dama: Combina torre y alfil.Rey: 1 casilla en cualquier dirección.")
print("Enroque: Mueve rey y torre juntos (protección). Solo si no han movido antes")
print("Captura al paso: Peón captura otro peón que avanzó 2 casillas, como si hubiera movido 1.")
print("Promoción: Peón que llega al extremo se convierte en dama, torre, alfil o caballo.")
print("Jaque: Rey amenazado. Debe evitarse (mover, bloquear o capturar)")
print("Jaque mate: Rey en jaque sin defensa. Fin de la partida (victoria).")
print("Tablas: Por ahogado (rey sin movimientos legales y no en jaque), repetición de jugadas, acuerdo o insuficiencia material.")