print("seleccionar una esponja doble cara que tenga para refrejar sucieda, suave y aspero")
print("recoger los platos al fregadero")
print("remojar con agua tibia los platos más grasos y secos 2 min")
print("colocar detergente de su mayor confianza a la esponja del lado más suave")
print("Masajear la esponja hasta crear abudante espuma")
print("Seleccionar un plato y empezar a refregar con la esponja en forma circular")
print("refregar todos los platos con la esponja")
print("Enjuagar todos lo platos con agua fria o tibia")
print("Dejar escurriendo los plato durante 3 min en el lavaplatos")
print("Secar todos los platos con una servilleta de tela limpia")
print("Acomodar los platos en la estanteria de platos")
print("fin")